# Generated by Django 4.2.3 on 2023-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="categories",
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, upload_to="img/"),
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="news.category"
            ),
        ),
    ]
