# Generated by Django 4.2.3 on 2023-10-27 21:14

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_remove_news_categories_alter_news_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200, validators=[news.models.validate_title]
            ),
        ),
    ]
